# Generated by Django 4.2.5 on 2023-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/autores/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='media/portadas/'),
        ),
    ]
